name: Run R script

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Run writingCode.r
        run: |
          Rscript writingCode.r

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: r-outputs
          path: r_outputs
